document.addEventListener('DOMContentLoaded',()=>{
 const userName=document.getElementById('userName');
 const saved=JSON.parse(localStorage.getItem('indomark.user')||'null');
 if(saved?.fullName) userName.textContent=saved.fullName.split(' ')[0];
 const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=v;};
 const money=v=>Number.isFinite(Number(v))?'₹'+Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
 function marketStatus(){const now=new Date();const day=now.getDay();const mins=now.getHours()*60+now.getMinutes();const open=day>=1&&day<=5&&mins>=555&&mins<930;set('marketStatus',open?'Market Open':'Market Closed');set('marketGreeting',open?'Market is open · Tracking current NSE movers':'Learn. Analyse. Practice. Trade.');set('marketNext',open?'Live market movers refresh from shared IndianAPI feed':'NSE regular session: 9:15 AM–3:30 PM on trading days');document.getElementById('statusDot')?.classList.toggle('open',open);}
 function moverRow(stock,negative=false){const pct=Number(stock.change);const pctText=Number.isFinite(pct)?`${pct>=0?'+':''}${pct.toFixed(2)}%`:'—';const row=document.createElement('button');row.className='stock-row';row.type='button';row.dataset.symbol=stock.symbol;row.innerHTML=`<span><b>${stock.symbol}</b><small>${stock.company||stock.symbol} · ${money(stock.price)}</small></span><strong class="${negative?'negative':'positive'}">${pctText}</strong>`;row.addEventListener('click',()=>{localStorage.setItem('indomark_selected_stock',stock.symbol);location.href='stock.html';});return row;}
 function renderMovers(containerId,rows,negative,updatedId){const box=document.getElementById(containerId);if(!box)return;if(!rows.length)return;box.innerHTML='';rows.forEach(stock=>box.appendChild(moverRow(stock,negative)));set(updatedId,`Updated ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}`);}
 function applyTrending(data){const gainers=Array.isArray(data?.gainers)?data.gainers:[];const losers=Array.isArray(data?.losers)?data.losers:[];if(gainers.length)renderMovers('gainersList',gainers.slice(0,4),false,'gainersUpdated');if(losers.length)renderMovers('losersList',losers.slice(0,4),true,'losersUpdated');}
 function showCached(){const api=window.IndomarkMarket;if(!api?.cached)return;const cached=['RELIANCE','TCS','INFY','HDFCBANK','ICICIBANK'].map(s=>api.cached(s)).filter(Boolean);if(cached.length){const sorted=[...cached].sort((a,b)=>Number(b.change)-Number(a.change));renderMovers('gainersList',sorted.slice(0,4),false,'gainersUpdated');renderMovers('losersList',[...sorted].reverse().slice(0,4),true,'losersUpdated');}}
 async function refreshNow(){const api=window.IndomarkMarket;if(!api?.getTrending)return;try{applyTrending(await api.getTrending());}catch(e){console.warn('Home trending refresh failed',e);}}
 marketStatus();showCached();refreshNow();let timer=setInterval(()=>{marketStatus();refreshNow();},60000);const onVisible=()=>{if(document.visibilityState==='visible'){marketStatus();refreshNow();}};document.addEventListener('visibilitychange',onVisible);window.addEventListener('focus',onVisible);window.addEventListener('beforeunload',()=>{clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);window.removeEventListener('focus',onVisible);});
});
